name = "o2c-router"
main = "src/worker.js"
compatibility_date = "2024-01-01"
account_id = "3472fe0b25f5c0f49a99d537cbe2cf35"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "subzero.o2c.one/*"
zone_name = "o2c.one"
